### ISSUE TITLE
Error: Cannot find module '8bitworkshop/node_modules/electron/install.js'

### ISSUE THREAD

**Issue by paklau99988** [sehugg/8bitworkshop#48]
```

# cd 8bitworkshop/
8bitworkshop# git submodule init
/8bitworkshop# git submodule update
8bitworkshop# npm i

> core-js@3.6.5 postinstall 8bitworkshop/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> electron@9.2.1 postinstall 8bitworkshop/node_modules/electron
> node install.js

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '8bitworkshop/node_modules/electron/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.2.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@9.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by sehugg** [comment]
Are you running as root? npm might be doing some funny stuff with user-switching. I'd try again with a fresh install as a regular user.
