### ISSUE TITLE
Cannot build with current instructions

### ISSUE THREAD

**Issue by pbpalomino** [sehugg/8bitworkshop#49]
Running the instructions provided in Readme.md it does not work.

How to fix this ?

Build error  #log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.8
3 info using node@v10.21.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle 8bitworkshop@3.7.0~prebuild: 8bitworkshop@3.7.0
6 info lifecycle 8bitworkshop@3.7.0~build: 8bitworkshop@3.7.0
7 verbose lifecycle 8bitworkshop@3.7.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle 8bitworkshop@3.7.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/devuser/8bitworkshop/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle 8bitworkshop@3.7.0~build: CWD: /home/devuser/8bitworkshop
10 silly lifecycle 8bitworkshop@3.7.0~build: Args: [ '-c', 'make' ]
11 silly lifecycle 8bitworkshop@3.7.0~build: Returned: code: 2  signal: null
12 info lifecycle 8bitworkshop@3.7.0~build: Failed to exec build script
13 verbose stack Error: 8bitworkshop@3.7.0 build: `make`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid 8bitworkshop@3.7.0
15 verbose cwd /home/devuser/8bitworkshop
16 verbose Linux 4.19.0-11-686-pae
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.21.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 2
22 error 8bitworkshop@3.7.0 build: `make`
22 error Exit status 2
23 error Failed at the 8bitworkshop@3.7.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by sehugg** [comment]
Do you have "make" installed?

**Comment by pbpalomino** [comment]
> Do you have "make" installed?

Yes, all installed.

**Comment by sehugg** [comment]
I mean the command-line GNU make, not the Node package. Try: `apt-get install make`

**Comment by pbpalomino** [comment]
> I mean the command-line GNU make, not the Node package. Try: `apt-get install make`

Posted steps to reproduce build errors from clean install.

**Comment by youkaicountry** [comment]
I can confirm strange issues building with current instructions on Ubuntu 20.04, and Raspbian 64-bit.
From a clean Ubuntu 20.04, tag 3.7.0 will not build and gives the following log:

```
patch -i meta/electron.diff -o electron.html
patching file electron.html (read from index.html)
Hunk #1 FAILED at 3.
Hunk #2 FAILED at 22.
Hunk #3 succeeded at 65 (offset -25 lines).
Hunk #4 succeeded at 90 (offset -25 lines).
Hunk #5 FAILED at 210.
Hunk #6 succeeded at 403 (offset -25 lines).
3 out of 6 hunks FAILED -- saving rejects to file electron.html.rej
make: *** [Makefile:6: all] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! 8bitworkshop@3.7.0 build: `make`
npm ERR! Exit status 2
```

Rolling back to tag 3.6.0 does successfully compile on both the Ubuntu machine and the Raspberry Pi. 
Node version: `v10.19.0`
NPM version: `6.14.4`

**Comment by sehugg** [comment]
Fixed, current HEAD now builds on Travis CI.

**Comment by youkaicountry** [comment]
And now I can confirm that the latest commit `1d952ad` successfully builds on both systems. Thanks!
